use one_infrastructure;

-- ----------------------------
-- Records of t_upms_permission_resource
-- ----------------------------
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (685, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '主题服务', 'fast.admin.serviceManagement.subjectService', 695, 0, NULL, 'fast.admin.serviceManagement.subjectService', NULL, 'fast.admin.serviceManagement.subjectService', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (686, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '数据API', 'fast.admin.serviceManagement.dataApiService', 695, 0, NULL, 'fast.admin.serviceManagement.dataApiService', NULL, 'fast.admin.serviceManagement.dataApiService', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (687, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', 'JDBC', 'fast.admin.serviceManagement.jdbcService', 695, 0, NULL, 'fast.admin.serviceManagement.jdbcService', NULL, 'fast.admin.serviceManagement.jdbcService', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (688, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '数据集', 'fast.admin.serviceManagement.dataSetService', 695, 0, NULL, 'fast.admin.serviceManagement.dataSetService', NULL, 'fast.admin.serviceManagement.dataSetService', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (689, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '目录管理', 'fast.admin.servicePlan', NULL, 0, NULL, '#', 'icon-kjyw1', 'cc_per_nav_statistic', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (690, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '服务目录', 'fast.admin.servicePlan.catalogList', 689, 0, NULL, 'fast.admin.servicePlan.catalogList', NULL, 'cc_per_nav_serv_stat', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (691, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '服务标签', 'fast.admin.servicePlan.serviceTag', 689, 0, NULL, 'fast.admin.servicePlan.serviceTag', NULL, 'cc_per_nav_serv_stat', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (692, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '应用管理', 'fast.admin.application', NULL, 0, NULL, '#', 'icon-pulsar-fwgh', 'cc_per_nav_statistic', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (693, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '应用管理', 'fast.admin.application.list', 692, 0, NULL, '#', NULL, 'cc_per_nav_statistic', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (695, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '服务管理', 'fast.admin.serviceManagement', NULL, 0, NULL, 'fast.admin.serviceManagement', 'icon-zygl2', 'fast.admin.serviceManagement', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (696, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '业务API', 'fast.admin.serviceManagement.gatewayService', 695, 0, NULL, 'fast.admin.serviceManagement.gatewayService', NULL, 'fast.admin.serviceManagement.gatewayService', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (697, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '通用服务', 'fast.admin.serviceManagement.whbuService', 695, 0, NULL, 'fast.admin.serviceManagement.whbuService', NULL, 'fast.admin.serviceManagement.whbuService', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (700, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '服务实例管理', 'fast.admin.instanceManagement', NULL, 0, NULL, '#', 'icon-yygh1', 'fast.admin.instanceManagement', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (701, '2019-05-22 09:43:48', 'admin', 0, '2019-05-22 09:43:48', 'admin', '主题服务', 'fast.admin.instanceManagement.subjectServiceInstance', 700, 0, NULL, 'fast.admin.instanceManagement.subjectServiceInstance', NULL, 'fast.admin.instanceManagement.subjectServiceInstance', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (702, '2019-05-20 14:47:16', 'admin', 0, '2019-05-20 14:47:16', 'admin', '数据API', 'fast.admin.instanceManagement.dataApiServiceInstance', 700, 0, NULL, 'fast.admin.instanceManagement.dataApiServiceInstance', NULL, 'fast.admin.instanceManagement.dataApiServiceInstance', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (705, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '流程管理', 'fast.admin.processManagement', NULL, 0, NULL, '#', 'icon-yyzl1', 'fast.admin.processManagement', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (706, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '流程管理', 'fast.admin.processManagement.main', 705, 0, NULL, 'fast.admin.processManagement.main', 'icon-zygl2', 'fast.admin.processManagement.main', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (710, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '服务调用日志', 'fast.admin.auditManagement.serviceAccessLog', 730, 0, NULL, 'fast.admin.auditManagement.serviceAccessLog', NULL, 'fast.admin.auditManagement.serviceAccessLog', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (711, '2018-09-05 15:00:27', 'admin', 0, '2018-09-04 15:00:27', 'admin', '总览', 'fast.mir.dashboard', NULL, 1, NULL, 'fast.mir.dashboard', 'icon-yyzl1', 'fast.mir.dashboard', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (713, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '订单管理', 'fast.mir.orderManagement', NULL, 1, NULL, '#', 'icon-kjyw1', 'fast.mir.orderManagement', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (714, '2019-05-22 09:45:21', 'admin', 0, '2019-05-22 09:45:21', 'admin', '主题服务', 'fast.mir.instanceManagement.subjectServiceInstance', 735, 1, NULL, 'fast.mir.instanceManagement.subjectServiceInstance', NULL, 'fast.mir.instanceManagement.subjectServiceInstance', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (715, '2019-05-21 15:16:45', 'admin', 0, '2019-05-21 15:16:45', 'admin', '数据API', 'fast.mir.instanceManagement.dataApiServiceInstance', 735, 1, NULL, 'fast.mir.instanceManagement.dataApiServiceInstance', NULL, 'fast.mir.instanceManagement.dataApiServiceInstance', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (718, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '我的申请单', 'fast.mir.orderManagement.application', 713, 1, NULL, 'fast.mir.orderManagement.application', NULL, 'fast.mir.orderManagement.application', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (719, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '待办申请单', 'fast.admin.order.unfinished({page:2})', 722, 0, NULL, 'fast.admin.order.unfinished', NULL, 'fast.admin.order.unfinished', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (720, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '已办申请单', 'fast.admin.order.finished', 722, 0, NULL, 'fast.admin.order.finished', NULL, 'fast.admin.order.finished', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (721, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '全部申请单', 'fast.admin.order.application({page:1})', 722, 0, NULL, 'fast.admin.order.application', NULL, 'fast.admin.order.application', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (722, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '审批管理', 'fast.admin.order.application({page:1})', NULL, 0, NULL, '#', 'icon-yhzx2', 'abc', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (723, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '总览', 'fast.admin.dashboard', NULL, 0, NULL, 'fast.admin.dashboard', 'icon-kjyw1', 'fast.admin.dashboard', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (727, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '服务监控', 'fast.admin.serviceMonitor', NULL, 0, NULL, '#', 'icon-tjbb2', 'fast.admin.serviceMonitor', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (728, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '服务状态监控', 'fast.admin.serviceMonitor.serviceStatusMonitor', 727, 0, NULL, 'fast.admin.serviceMonitor.serviceStatusMonitor', NULL, 'fast.admin.serviceMonitor.serviceStatusMonitor', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (729, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '服务监控统计', 'fast.admin.serviceMonitor.monitorStatistics', 727, 0, NULL, 'fast.admin.serviceMonitor.monitorStatistics', NULL, 'fast.admin.serviceMonitor.monitorStatistics', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (730, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '日志管理', 'fast.wh.auditManagement', NULL, 0, NULL, '#', 'icon-sjgl1', 'fast.wh.auditManagement', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (733, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '服务数据配置', 'fast.admin.servicePlan.dataConfig.system', 689, 0, NULL, 'fast.admin.servicePlan.dataConfig.system', NULL, 'fast.admin.servicePlan.dataConfig.system', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (734, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '续期管理', 'fast.mir.orderManagement.renewal', 713, 1, NULL, 'fast.mir.orderManagement.renewal', NULL, 'fast.mir.orderManagement.renewal', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (735, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '服务实例', 'fast.mir.fastBusiness', NULL, 1, NULL, '#', 'icon-yygh1', 'fast.mir.fastBusiness', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (736, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '第三方认证', 'fast.mir.developmentCenter.clients', NULL, 1, NULL, 'fast.mir.developmentCenter.clients', 'icon-yyzy1', 'fast.mir.developmentCenter.clients', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (797, '2019-05-20 14:57:35', 'admin', 0, '2019-05-20 14:57:35', 'admin', 'JDBC', 'fast.admin.instanceManagement.jdbcServiceInstance', 700, 0, NULL, 'fast.admin.instanceManagement.jdbcServiceInstance', NULL, 'fast.admin.instanceManagement.jdbcServiceInstance', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (798, '2019-05-20 14:58:15', 'admin', 0, '2019-05-20 14:58:15', 'admin', '数据集', 'fast.admin.instanceManagement.dataSetServiceInstance', 700, 0, NULL, 'fast.admin.instanceManagement.dataSetServiceInstance', NULL, 'fast.admin.instanceManagement.dataSetServiceInstance', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (799, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '业务API', 'fast.admin.instanceManagement.gatewayServiceInstance', 700, 0, NULL, 'fast.admin.instanceManagement.gatewayServiceInstance', NULL, 'fast.admin.instanceManagement.gatewayServiceInstance', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (800, '2019-05-21 15:18:44', 'admin', 0, '2019-05-21 15:18:44', 'admin', 'JDBC', 'fast.mir.instanceManagement.jdbcServiceInstance', 735, 1, NULL, 'fast.mir.instanceManagement.jdbcServiceInstance', NULL, 'fast.mir.instanceManagement.jdbcServiceInstance', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (801, '2019-05-21 15:19:27', 'admin', 0, '2019-05-21 15:19:27', 'admin', '数据集', 'fast.mir.instanceManagement.dataSetServiceInstance', 735, 1, NULL, 'fast.mir.instanceManagement.dataSetServiceInstance', NULL, 'fast.mir.instanceManagement.dataSetServiceInstance', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (802, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '业务API', 'fast.mir.instanceManagement.apiService', 735, 1, NULL, 'fast.mir.instanceManagement.apiService', NULL, 'fast.mir.instanceManagement.apiService', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (803, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '通用服务', 'fast.admin.instanceManagement.serviceInstance', 700, 0, NULL, 'fast.admin.instanceManagement.serviceInstance', NULL, 'fast.admin.instanceManagement.serviceInstance', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (804, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '通用服务', 'fast.mir.instanceManagement.whbuService', 735, 1, NULL, 'fast.mir.instanceManagement.whbuService', NULL, 'fast.mir.instanceManagement.whbuService', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (1024, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '文件服务', 'fast.admin.serviceManagement.fileService', 695, 0, NULL, 'fast.admin.serviceManagement.fileService', NULL, 'fast.admin.serviceManagement.fileService', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (1025, '2018-09-05 15:00:27', 'admin', 0, '2018-09-05 15:00:27', 'admin', '文件服务', 'fast.mir.instanceManagement.fileServiceInstance', 735, 1, NULL, 'fast.mir.instanceManagement.fileServiceInstance', NULL, 'fast.mir.instanceManagement.fileServiceInstance', 2);
INSERT INTO  `t_upms_permission_resource` (`oid`, `create_time`, `create_user`, `deleted`, `last_modify_time`, `last_modify_user`, `name`, `state`, `parent_id`, `type`, `position`, `href`, `icon`, `nav_id`, `system_id`) VALUES (1026, '2019-05-20 14:57:35', 'admin', 0, '2019-05-20 14:57:35', 'admin', '文件服务', 'fast.admin.instanceManagement.fileServiceInstance', 700, 0, NULL, 'fast.admin.instanceManagement.fileServiceInstance', NULL, 'fast.admin.instanceManagement.fileServiceInstance', 2);
-- ----------------------------
-- Records of t_config_menu
-- ----------------------------
INSERT INTO `t_config_menu` VALUES ('1', '2019-04-17 15:48:14', null, '0', '2019-04-17 15:48:14', null, '1', '数据一张图', '0', '/statistics-ui/', '1', '2', 'ADMIN_CONSOLE');
INSERT INTO `t_config_menu` VALUES ('2', '2019-04-19 09:49:26', null, '0', '2019-04-19 11:23:44', null, '3', 'WH-用户端', '0', '/wh-ui/', '0', '2', 'USER_CONSOLE');
INSERT INTO `t_config_menu` VALUES ('3', '2019-04-25 13:39:33', null, '0', '2019-04-25 13:41:26', null, '5', '用户总览', '0', '/wh-ui/dashboard', '0', '2', 'USER_CONSOLE');


INSERT INTO `t_config_system` VALUES ('2', '2019-04-17 15:48:14', 'bf8d1a19-ad46-4297-ada2-d1095409121c', '0', '2019-04-17 15:48:14',
'bf8d1a19-ad46-4297-ada2-d1095409121c', 'assets/images/fast.png', 'v2.0', '大数据服务应用支撑平台', '1');

update t_config_system set sub_system_name='V2.0', system_name='大数据服务应用支撑平台' where oid=1;