---

- name: Create greenplum admin user
  user:
    name: "{{ greenplum_admin_user }}"
    password: "{{ greenplum_admin_password | password_hash('sha512') }}"
    update_password: on_create

- name: Install greenplum package
  yum:
    name: greenplum-db
    state: present
    use_backend: yum

- name: Install ed package
  yum:
    name: "ed"
    state: present
    use_backend: yum

- name: Find install directory
  find:
    paths: /usr/local
    patterns: 'greenplum*'
    file_type: directory
  register: installed_dir

- name: Change install directory ownership
  file:
    path: "{{ item.path }}"
    owner: "{{ greenplum_admin_user }}"
    group: "{{ greenplum_admin_user }}"
    recurse: yes
  with_items: "{{ installed_dir.files }}"

- name: Update pam_limits
  pam_limits:
    domain: "{{ greenplum_admin_user }}"
    limit_type: '-'
    limit_item: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict:
    nofile: 524288
    nproc: 131072

- name: Add /usr/local/bin to greenplum LD_LIBRARY_PATH
  lineinfile:
    path: /usr/local/greenplum-db/greenplum_path.sh
    regexp: '^LD_LIBRARY_PATH='
    line: "LD_LIBRARY_PATH=$GPHOME/lib:$PYTHONHOME/lib:/usr/local/lib:${LD_LIBRARY_PATH-}"

- name: link greenplum libs
  shell: |
    rm -rf /usr/local/greenplum-db/bin/lib/libgpopt.so.3
    rm -rf /usr/local/greenplum-db/bin/lib/libpq.so.5
    ln -s /usr/local/lib/libgpopt.so.3 /usr/local/greenplum-db/bin/lib/libgpopt.so.3
    ln -s /usr/local/lib/libpq.so.5 /usr/local/greenplum-db/bin/lib/libpq.so.5

- name: Find installed greenplum version
  shell: . /usr/local/greenplum-db/greenplum_path.sh && /usr/local/greenplum-db/bin/postgres --gp-version
  register: postgres_gp_version

- name: Fail if the correct greenplum version is not installed
  fail:
    msg: "Expected greenplum version {{ version }}, but found '{{ postgres_gp_version.stdout }}'"
  when: "version is not defined or version not in postgres_gp_version.stdout"

- name: Insert greenplum path to gpadmin user's .bashrc
  lineinfile:
    path: "/home/{{ greenplum_admin_user }}/.bashrc"
    line: ". /usr/local/greenplum-db/greenplum_path.sh"
