---

- name:  stop mysql
  shell: cd /opt/chinacloud/mysql_mgr   && docker-compose -f ./docker-compose.yml  down
  ignore_errors: True

- name: del mysql
  shell: rm -rf /opt/chinacloud/mysql_mgr
  ignore_errors: True

- name: clean rc.local start_mysql
  shell: sed -i '/^docker-compose -f \/opt\/chinacloud\/mysql_mgr\/docker-compose.yml.*/d' /etc/rc.local
  ignore_errors: True
