---

- name: check zookeeper dir
  shell: grep -r "/opt/chinacloud/zookeeper" /etc/rc.local
  register: check_zookeeper_mount_point
  ignore_errors: True
  failed_when: check_zookeeper_mount_point.rc == 0

- name: create  zookeeper directory
  file: path=/opt/chinacloud/zookeeper state=directory mode=0755

- name: copy fast zookeeper file to /opt
  copy: src=zookeeper/ dest=/opt/chinacloud/zookeeper/  mode=0755

- name: add zookeeper configure
  template: src=zoo.cfg.j2 dest=/opt/chinacloud/zookeeper/conf/zoo.cfg

- name: add zookeeper myid
  template: src=myid.j2 dest=/opt/chinacloud/zookeeper/data/myid

- name: add zookeeper docker-compose.yml
  template: src=docker-compose.yml.j2 dest=/opt/chinacloud/zookeeper/docker-compose.yml

- name:  stop zookeeper
  shell: cd /opt/chinacloud/zookeeper   && docker-compose -f ./docker-compose.yml  down

- name:  start zookeeper
  shell: cd /opt/chinacloud/zookeeper && docker-compose -f ./docker-compose.yml  up  -d

- name: wait cluster alive
  action: shell docker-compose -f /opt/chinacloud/zookeeper/docker-compose.yml ps| grep zoo
  register: result
  until: result.stdout.find("(healthy)") != -1
  retries: 20
  delay: 20
