---

## ------------------------------------------------------------------------------------------------------------
## Ansible配置
## ------------------------------------------------------------------------------------------------------------

ansible_become: false
tmp_dir: /tmp

## ------------------------------------------------------------------------------------------------------------
## Nexus配置
## ------------------------------------------------------------------------------------------------------------

# nexus服务器地址，配置inventory中registry server的地址
nexus_addr: "172.16.60.24"

# nexus服务器端口
nexus_port: 8081

# cdh相关rpm包仓库
# Devops工程的开发环境配置为 "cdh-yum-proxy"，测试与生产环境配置为 "cdh-yum"
nexus_cdh_yum_repository: "cdh-yum-proxy"

# cdh parcels包仓库
# Devops工程的开发环境配置为 "cdh-parcels-proxy"，测试与生产环境配置为 "cdh-parcels"
nexus_cdh_parcels_repository: "cdh-parcels-proxy"

# Yum base repo
# Devops工程的开发环境配置为 "base-proxy"，测试与生产环境配置为 "base"
nexus_yum_base_repository: "base-proxy"

# Yum epel repo
# Devops工程的开发环境配置为 "epel-proxy"，测试与生产环境配置为 "epel"
nexus_yum_epel_repository: "epel-proxy"

# 其他杂项文件的HTTP仓库，各类环境的配置相同
nexus_yum_miscs_repository: "miscs"

## ------------------------------------------------------------------------------------------------------------
## Yum options
## ------------------------------------------------------------------------------------------------------------

# Yum base repo与epel repo地址
# 无需修改，代表使用产品中集成的nexus作为yum源。如特殊情况，可指定为其他可用yum源地址。
base_repo: "http://{{ nexus_addr }}:{{ nexus_port }}/repository/{{ nexus_yum_base_repository }}/$releasever/os/$basearch"
epel_repo: "http://{{ nexus_addr }}:{{ nexus_port }}/repository/{{ nexus_yum_epel_repository }}/{{ ansible_distribution_major_version }}/$basearch"

## ------------------------------------------------------------------------------------------------------------
## NTP配置
## ------------------------------------------------------------------------------------------------------------

# ntp根服务器地址
# 产品独立部署，不需要配置此项。默认使用inventory文件中的registry server作为本地ntp根服务器。
# 特殊情况，产品与其他系统集成时，如需要与其他系统进行时间同步，配置此项为其他ntp根服务器地址。
# ntp_idc_server: 58.220.207.226

## ------------------------------------------------------------------------------------------------------------
## CDH - 安全配置，未启用，勿修改
## ------------------------------------------------------------------------------------------------------------

krb5_realm: MIT.EXAMPLE.COM
# 'Active Directory', 'MIT KDC', or 'none' to disable security
# krb5_kdc_type: MIT KDC
krb5_kdc_type: none
krb5_kdc_admin_user: "cloudera-scm/admin@{{ krb5_realm }}"
krb5_kdc_admin_passwd: changeme
krb5_kdc_master_passwd: changeme

# krb5_realm: AD.EXAMPLE.COM
# krb5_kdc_type: Active Directory
# krb5_kdc_host: my.ad.example.com
# krb5_kdc_admin_user: "admin@{{ krb5_realm }}"
# krb5_kdc_admin_passwd: changeme
# krb5_ad_suffix: "OU=Clusters,DC=ad,DC=example,DC=com"
# krb5_ad_delete_on_regenerate: true

# krb5_cm_managed_krb5_conf: false
# krb5_enc_types: "aes256-cts aes128-cts rc4-hmac"

ad_domain: "{{ krb5_realm.lower() }}"
kdc: w2k8-1.ad.sec.example.com
computer_ou: OU=computer_hosts,OU=hadoop_prd,DC=ad,DC=sec,DC=example,DC=com
ldap_group_search_base: OU=groups,OU=hadoop_prd,DC=ad,DC=sec,DC=example,DC=com
ldap_user_search_base: DC=ad,DC=sec,DC=example,DC=com?subtree?(memberOf=CN=hadoop_users,OU=groups,OU=hadoop_prd,DC=ad,DC=sec,DC=example,DC=com)
override_gid: 999999
ad_site: Default-First-Site-Name

## ------------------------------------------------------------------------------------------------------------
## CDH - Cloudera Manager配置
## ------------------------------------------------------------------------------------------------------------

# CDH安装版本
# 勿改动，目前仅支持 6.3.0
cluster_version_cdh: 6.3.0

# Cloudera Manager安装版本
# 勿改动，同CDH版本
cluster_version_cm:  "{{ cluster_version_cdh }}"

# Version of CDS Powered by Apache Spark (note: not installed if CDH6/7 is also selected)
cluster_version_cds: 2.4.0.cloudera2

# Helper variables for major and minor versions
cluster_version_cdh_major: "{{ cluster_version_cdh.split('.')[0] }}"
cluster_version_cdh_minor: "{{ cluster_version_cdh.split('.')[1] }}"
cluster_version_cm_major: "{{ cluster_version_cm.split('.')[0] }}"
cluster_version_cm_minor: "{{ cluster_version_cm.split('.')[1] }}"

# Cloudera Manager版本相关配置
configs_by_version:
  "6":
    scm_repo_url:    "http://{{ nexus_addr }}:{{ nexus_port }}/repository/{{ nexus_cdh_yum_repository }}/cm6/{{ cluster_version_cm }}/redhat{{ ansible_distribution_major_version }}/yum"
    scm_repo_gpgkey: "http://{{ nexus_addr }}:{{ nexus_port }}/repository/{{ nexus_cdh_yum_repository }}/cm6/{{ cluster_version_cm }}/redhat{{ ansible_distribution_major_version }}/yum/RPM-GPG-KEY-cloudera"
    scm_parcel_repositories:
      - "http://{{ nexus_addr }}:{{ nexus_port }}/repository/{{ nexus_cdh_parcels_repository }}/cdh6/{{ cluster_version_cdh }}/parcels"
      - "http://{{ nexus_addr }}:{{ nexus_port }}/repository/{{ nexus_cdh_parcels_repository }}/cdh-parcels/{{ cluster_version_cdh }}"
    scm_prepare_database_script_path: "/opt/cloudera/cm/schema/scm_prepare_database.sh"

scm_parcel_repositories:            "{{ configs_by_version[cluster_version_cdh_major].scm_parcel_repositories }}"
scm_prepare_database_script_path:   "{{ configs_by_version[cluster_version_cm_major].scm_prepare_database_script_path }}"
scm_repo_url:                       "{{ configs_by_version[cluster_version_cm_major].scm_repo_url }}"
scm_repo_gpgkey:                    "{{ configs_by_version[cluster_version_cm_major].scm_repo_gpgkey }}"
scm_csds:                           "{{ configs_by_version[cluster_version_cm_major].scm_csds | default([]) }}"

# Cloudera Manager用户名
scm_default_user: admin
# Cloudera Manager密码
scm_default_pass: admin
# Cloudera Manager端口
scm_port: 7180
# Cloudera Manager License，未启用此选型
scm_license_file: /path/to/cloudera_license.txt

## ------------------------------------------------------------------------------------------------------------
## CDH - Java安装配置，勿改动
## ------------------------------------------------------------------------------------------------------------

java_installation_strategy: package       # can be set to 'none', 'package' or 'rpm'
java_package: java-1.8.0-openjdk-devel
java_rpm_location: /tmp/jdk-8u181-linux-x64.rpm
java_rpm_remote_src: no
java_jce_location: /tmp/jce_policy-8.zip
java_jce_remote_src: no
java_mysql_connector_download_url: http://{{ nexus_addr }}:{{ nexus_port }}/repository/{{ nexus_yum_miscs_repository }}/cdh/mysql-connector-java-5.1.48.zip

## ------------------------------------------------------------------------------------------------------------
## 机器学习 - Python配置（Beta）
## ------------------------------------------------------------------------------------------------------------

# TODO: 替换成nexus pypi repository
pypi_index: https://pypi.douban.com/simple
