---

# Cloudera playbook
- name: Perf configs
  hosts: cdh_servers
  roles:
    - cdh/perf
  tags: perf

- name: Install rngd
  hosts: cdh_servers
  roles:
    - cdh/rngd
  tags: rngd

- name: Install Java
  hosts: cdh_servers
  roles:
    - cdh/java
  tags: java

- name: Install MariaDB and create databases
  hosts: db_server
  roles:
    - cdh/mariadb
  tags:
    - mysql
    - mysql_server

- name: Install MySQL Connector
  hosts: cdh_servers
  roles:
    - cdh/mysql_connector
  tags:
    - mysql
    - mysql_client

- name: Install MIT KDC Server
  hosts: krb5_server
  roles:
    - { role: cdh/krb5/server, when: (krb5_kdc_type is defined) and (krb5_kdc_type != 'none') }
  tags: krb5

- name: Install MIT KDC Client
  hosts: all
  roles:
    - { role: cdh/krb5/client, when: (krb5_kdc_type is defined) and (krb5_kdc_type != 'none') }
  tags: krb5

- name: Install Cloudera Manager Agents
  hosts: cdh_servers
  roles:
    - cdh/cm_agents
  tags: cm_agents

- name: Install Cloudera Manager Server
  hosts: scm_server
  roles:
    - cdh/scm
  tags: cluster_template

# TODO: 使用Cluster Template创建CDH
# - name: Install CDH
#   hosts: scm_server
#   roles:
#     - cdh/cdh
#   tags: cluster_template

