---

- name: create hadoop conf directory
  file: path="{{ item }}" state=directory mode=0755
  with_items:
    - /etc/hadoop/conf
    - /etc/hive/conf
    - /etc/hbase/conf
    - /etc/zookeeper/conf

- name: Copy Remote-To-Remote (from scm_server to host)
  synchronize: src="{{ item }}" dest="{{ item }}"
  delegate_to: "{{ hadoop_master_hostname }}"
  with_items:
    - /etc/hadoop/conf/
    - /etc/hive/conf/
    - /etc/hbase/conf/
    - /etc/zookeeper/conf/
